"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Role = "Student" | "Faculty" | "Coordinator" | "Admin";
type RecordItem = { id:number; kind:string; title:string; subtitle:string; status:string; meta:Record<string,unknown>; created_at:number };
type Activity = { id:number; message:string; actor:string; created_at:number };
const modules = [
  ["Overview","⌂"],["Attendance","✓"],["Assignments","▤"],["Events","◇"],["Placements","↗"],["Clubs","◎"],["Calendar","▱"],["Messages","♧"],["Admin","⚙"],
];
const people:Record<Role,{name:string;sub:string;initials:string}> = {
  Student:{name:"Aarav Mehta",sub:"B.Tech CSE · Semester 6",initials:"AM"},
  Faculty:{name:"Dr. Maya Kapoor",sub:"Computer Science Faculty",initials:"MK"},
  Coordinator:{name:"Riya Sharma",sub:"Campus Event Coordinator",initials:"RS"},
  Admin:{name:"Vikram Rao",sub:"Platform Administrator",initials:"VR"},
};
const schedule = [
  {time:"09:00",end:"10:00",title:"Machine Learning",place:"Lab 302",faculty:"Dr. Maya Kapoor",color:"blue"},
  {time:"11:00",end:"12:00",title:"Computer Networks",place:"Room 214",faculty:"Prof. Arjun Nair",color:"purple"},
  {time:"14:30",end:"15:30",title:"Database Systems",place:"Room 108",faculty:"Dr. Nisha Verma",color:"orange"},
];
const attendance = [
  {subject:"Machine Learning",code:"CS601",present:22,total:24,pct:92},
  {subject:"Database Systems",code:"CS603",present:21,total:24,pct:88},
  {subject:"Computer Networks",code:"CS605",present:19,total:24,pct:79},
  {subject:"Software Engineering",code:"CS607",present:23,total:25,pct:92},
];

export default function Home(){
  const [active,setActive]=useState("Overview");
  const [role,setRole]=useState<Role>("Student");
  const [records,setRecords]=useState<RecordItem[]>([]);
  const [activity,setActivity]=useState<Activity[]>([]);
  const [loading,setLoading]=useState(true);
  const [toast,setToast]=useState("");
  const [modal,setModal]=useState<string|null>(null);
  const [search,setSearch]=useState("");
  const [dark,setDark]=useState(false);
  const person=people[role];

  async function load(){
    try{ const r=await fetch("/api/campus"); const data=await r.json(); setRecords(data.records||[]); setActivity(data.activity||[]); }
    catch{ setToast("Could not load campus data"); } finally{setLoading(false)}
  }
  useEffect(()=>{load()},[]);
  function flash(msg:string){setToast(msg);setTimeout(()=>setToast(""),2600)}
  async function changeStatus(item:RecordItem,status:string){
    setRecords(v=>v.map(x=>x.id===item.id?{...x,status}:x));
    const r=await fetch("/api/campus",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,status,actor:person.name})});
    if(!r.ok){flash("Update failed");await load()} else flash(`Successfully ${status}`);
  }
  async function createRecord(e:FormEvent<HTMLFormElement>){
    e.preventDefault(); const fd=new FormData(e.currentTarget); const kind=String(fd.get("kind"));
    const body={kind,title:String(fd.get("title")),subtitle:String(fd.get("subtitle")),status:kind==="announcement"?"published":"open",actor:person.name,meta:{category:fd.get("category")||"Campus"}};
    const r=await fetch("/api/campus",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
    if(r.ok){setModal(null);flash(`${kind} created`);await load()} else flash("Please complete all fields");
  }
  const byKind=(kind:string)=>records.filter(r=>r.kind===kind && (!search||`${r.title} ${r.subtitle}`.toLowerCase().includes(search.toLowerCase())));
  const canCreate=(kind:string)=>role==="Admin"||(kind==="assignment"&&role==="Faculty")||(kind==="event"&&role==="Coordinator")||(kind==="announcement"&&["Faculty","Coordinator"].includes(role));

  return <main className={dark?"app-shell dark":"app-shell"}>
    <aside className="sidebar">
      <button className="brand" onClick={()=>setActive("Overview")}><span className="brand-mark">C</span><span>Campus<b>One</b></span></button>
      <nav><p className="nav-label">CAMPUS WORKSPACE</p>{modules.map(([name,icon])=><button key={name} className={`nav-item ${active===name?"active":""} ${name==="Admin"&&role!=="Admin"?"role-hidden":""}`} onClick={()=>setActive(name)}><span className="nav-icon">{icon}</span>{name}{name==="Assignments"&&<b>{byKind("assignment").filter(x=>x.status==="pending").length}</b>}</button>)}</nav>
      <div className="help-card"><span>?</span><strong>Campus help desk</strong><p>Questions or technical trouble? We usually reply in under 5 minutes.</p><button onClick={()=>{setActive("Messages");flash("Help desk conversation opened")}}>Contact support →</button></div>
      <button className="profile-mini" onClick={()=>setModal("profile")}><span className="avatar">{person.initials}</span><span><strong>{person.name}</strong><small>{role}</small></span><span className="dots">•••</span></button>
    </aside>

    <section className="workspace">
      <header className="topbar"><button className="mobile-logo" onClick={()=>flash("Use bottom navigation")}>C</button><label className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search campus records..."/><kbd>⌘ K</kbd></label><div className="top-actions"><select value={role} onChange={e=>{setRole(e.target.value as Role);setActive("Overview");flash(`Switched to ${e.target.value} view`)}}>{Object.keys(people).map(r=><option key={r}>{r}</option>)}</select><button className="icon-btn" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?"☀":"◐"}</button><button className="icon-btn notification" onClick={()=>setActive("Messages")}>♢<i/></button><span className="top-avatar">{person.initials}</span></div></header>
      <div className="content">
        {loading?<Loading/>:<>
          <div className="module-header"><div><p className="eyebrow">NORTHBRIDGE INSTITUTE OF TECHNOLOGY</p><h1>{active}</h1><p>{subtitle(active,role)}</p></div>{canCreate(kindFor(active))&&<button className="primary" onClick={()=>setModal(kindFor(active))}>＋ Create {singular(active)}</button>}</div>
          {active==="Overview"&&<Overview role={role} records={records} activity={activity} setActive={setActive}/>} 
          {active==="Attendance"&&<AttendanceView role={role} flash={flash}/>} 
          {active==="Assignments"&&<RecordView title="Course assignments" items={byKind("assignment")} empty="No assignments found" render={(x)=><AssignmentCard key={x.id} item={x} role={role} action={changeStatus}/>}/>} 
          {active==="Events"&&<RecordView title="Campus events" items={byKind("event")} empty="No events found" render={(x)=><EventCard key={x.id} item={x} role={role} action={changeStatus}/>}/>} 
          {active==="Placements"&&<Placements items={byKind("placement")} role={role} action={changeStatus}/>} 
          {active==="Clubs"&&<RecordView title="Student clubs" items={byKind("club")} empty="No clubs found" render={(x)=><ClubCard key={x.id} item={x} action={changeStatus}/>}/>} 
          {active==="Calendar"&&<CalendarView records={records}/>} 
          {active==="Messages"&&<Messages items={byKind("message")} role={role} create={async(text)=>{const r=await fetch("/api/campus",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"message",title:person.name,subtitle:text,status:"sent",actor:person.name})});if(r.ok){flash("Message sent");await load()}}}/>} 
          {active==="Admin"&&<AdminView records={records} activity={activity} setModal={setModal}/>} 
        </>}
        <footer><span>CampusOne · Northbridge Institute of Technology</span><span>System status: <b>● All services operational</b></span></footer>
      </div>
    </section>
    <nav className="mobile-nav">{modules.slice(0,5).map(([name,icon])=><button key={name} className={active===name?"active":""} onClick={()=>setActive(name)}><span>{icon}</span>{name}</button>)}</nav>
    {modal&&<Modal type={modal} close={()=>setModal(null)} person={person} submit={createRecord}/>} 
    {toast&&<div className="toast"><span>✓</span>{toast}</div>}
  </main>
}

function Overview({role,records,activity,setActive}:{role:Role;records:RecordItem[];activity:Activity[];setActive:(x:string)=>void}){
 const assignments=records.filter(x=>x.kind==="assignment"),events=records.filter(x=>x.kind==="event"),placements=records.filter(x=>x.kind==="placement");
 return <><div className="welcome-banner"><div><span>MONDAY, 10 AUGUST</span><h2>Good morning, {people[role].name.split(" ")[0]} 👋</h2><p>{role==="Student"?"You have 3 classes and 1 assignment due today.":`Manage today’s ${role.toLowerCase()} responsibilities from one place.`}</p></div><div className="banner-art"><i/><i/><i/></div></div>
 <div className="stat-grid"><Stat icon="✓" color="blue" label="Overall attendance" value={role==="Student"?"86.4%":"91.2%"} detail="↑ 2.4% this month"/><Stat icon="▤" color="purple" label={role==="Student"?"Pending assignments":"Open submissions"} value={String(assignments.filter(x=>x.status==="pending").length||3)} detail="1 due today"/><Stat icon="◇" color="orange" label="Upcoming events" value={String(events.length)} detail={`${events.filter(x=>x.status==="registered").length} registered`}/><Stat icon="↗" color="green" label="Placement opportunities" value={String(placements.length+12)} detail="8 new this week"/></div>
 <div className="main-grid"><section className="panel schedule-panel"><PanelTitle title="Today’s schedule" sub="Monday, 10 August" action="View calendar →" click={()=>setActive("Calendar")}/><div className="timeline">{schedule.map(s=><div className="class-row" key={s.title}><div className="time"><strong>{s.time}</strong><span>{s.end}</span></div><i className={s.color}/><div className="class-info"><strong>{s.title}</strong><span>{s.faculty} · {s.place}</span></div><span className="live-pill">{s.time==="09:00"?"NEXT":""}</span></div>)}</div></section>
 <section className="panel"><PanelTitle title="Pending work" sub="Stay ahead of deadlines" action="View all →" click={()=>setActive("Assignments")}/>{assignments.slice(0,3).map((a,i)=><div className="mini-record" key={a.id}><span className={`doc-icon d${i}`}>▤</span><div><strong>{a.title}</strong><small>{a.subtitle}</small></div><b className={a.status}>{a.status}</b></div>)}</section>
 <section className="panel"><PanelTitle title="Attendance overview" sub="August performance" action="Full report →" click={()=>setActive("Attendance")}/><div className="chart-area"><div className="donut"><div><strong>86.4%</strong><span>Present</span></div></div><div className="legend"><p><i className="present"/>Present <b>38</b></p><p><i className="absent"/>Absent <b>4</b></p><p><i className="leave"/>On leave <b>2</b></p></div></div></section>
 <section className="panel"><PanelTitle title="Recent activity" sub="Live campus updates" action="" click={()=>{}}/><div className="activity-list">{(activity.length?activity:[{id:1,message:"Attendance marked for Machine Learning",actor:"Dr. Maya Kapoor",created_at:Date.now()}]).slice(0,4).map(a=><div key={a.id}><span>●</span><p><strong>{a.message}</strong><small>{a.actor} · recently</small></p></div>)}</div></section></div></>
}
function AttendanceView({role,flash}:{role:Role;flash:(x:string)=>void}){const [marked,setMarked]=useState<string[]>([]);return <div className="two-column"><section className="panel wide"><PanelTitle title="Subject-wise attendance" sub="Academic year 2026–27" action="Download report" click={()=>flash("Attendance report prepared")}/><div className="data-table"><div className="table-head"><span>Subject</span><span>Classes</span><span>Attendance</span><span>Status</span></div>{attendance.map(a=><div className="table-row" key={a.code}><span><strong>{a.subject}</strong><small>{a.code}</small></span><span>{a.present} / {a.total}</span><span><div className="inline-progress"><i style={{width:`${a.pct}%`}}/></div><b>{a.pct}%</b></span><span className={a.pct>=75?"status-good":"status-bad"}>{a.pct>=75?"On track":"At risk"}</span></div>)}</div></section><section className="panel"><PanelTitle title={role==="Faculty"?"Take attendance":"Monthly summary"} sub={role==="Faculty"?"Machine Learning · Lab 302":"Your attendance trend"} action="" click={()=>{}}/>{role==="Faculty"?<div className="roster">{["Aarav Mehta","Diya Singh","Kabir Khan","Meera Joshi","Vivaan Shah"].map(n=><label key={n}><span className="avatar">{n.split(" ").map(x=>x[0]).join("")}</span><strong>{n}</strong><input type="checkbox" checked={marked.includes(n)} onChange={()=>setMarked(v=>v.includes(n)?v.filter(x=>x!==n):[...v,n])}/></label>)}<button className="primary full" onClick={()=>flash(`Attendance saved for ${marked.length} students`)}>Save attendance</button></div>:<div className="month-grid">{Array.from({length:31},(_,i)=><span className={i%7===5||i%11===0?"absent-day":"present-day"} key={i}>{i+1}</span>)}</div>}</section></div>}
function RecordView({title,items,empty,render}:{title:string;items:RecordItem[];empty:string;render:(x:RecordItem)=>React.ReactNode}){return <section className="panel module-panel"><PanelTitle title={title} sub={`${items.length} records`} action="" click={()=>{}}/><div className="card-list">{items.length?items.map(render):<Empty text={empty}/>}</div></section>}
function AssignmentCard({item,role,action}:{item:RecordItem;role:Role;action:(x:RecordItem,s:string)=>void}){return <article className="record-card"><span className="large-icon purple">▤</span><div className="record-copy"><span className="category">ASSIGNMENT</span><h3>{item.title}</h3><p>{item.subtitle}</p><div className="meta-row"><span>◷ {String(item.meta.due||"Upcoming")}</span><span>★ {String(item.meta.points||100)} points</span></div></div><div className="record-actions"><span className={`state ${item.status}`}>{item.status}</span>{role==="Student"&&<button className="primary" onClick={()=>action(item,"submitted")}>{item.status==="submitted"?"Resubmit":"Submit work"}</button>}{role==="Faculty"&&<button className="outline" onClick={()=>action(item,"graded")}>Review</button>}</div></article>}
function EventCard({item,role,action}:{item:RecordItem;role:Role;action:(x:RecordItem,s:string)=>void}){return <article className="record-card"><div className="date-block"><strong>{item.subtitle.slice(0,2)}</strong><span>AUG</span></div><div className="record-copy"><span className="category">{String(item.meta.category||"CAMPUS EVENT")}</span><h3>{item.title}</h3><p>{item.subtitle}</p><div className="meta-row"><span>◎ {String(item.meta.seats||80)} seats</span><span>Free entry</span></div></div><div className="record-actions"><span className={`state ${item.status}`}>{item.status}</span>{role==="Student"&&<button className={item.status==="registered"?"outline":"primary"} onClick={()=>action(item,item.status==="registered"?"open":"registered")}>{item.status==="registered"?"Cancel":"Register"}</button>}</div></article>}
function ClubCard({item,action}:{item:RecordItem;action:(x:RecordItem,s:string)=>void}){return <article className="record-card"><span className="large-icon blue">◎</span><div className="record-copy"><span className="category">{String(item.meta.category||"STUDENT CLUB")}</span><h3>{item.title}</h3><p>{item.subtitle}</p></div><div className="record-actions"><button className={item.status==="joined"?"outline":"primary"} onClick={()=>action(item,item.status==="joined"?"open":"joined")}>{item.status==="joined"?"✓ Joined":"Join club"}</button></div></article>}
function Placements({items,role,action}:{items:RecordItem[];role:Role;action:(x:RecordItem,s:string)=>void}){return <><div className="placement-hero"><div><span>CAREER SERVICES</span><h2>Your next opportunity starts here.</h2><p>Curated roles matched to your skills and academic profile.</p></div><div><strong>87%</strong><span>Profile strength</span></div></div><RecordView title="Recommended opportunities" items={items} empty="No roles match your search" render={x=><article className="record-card" key={x.id}><span className="company-logo">{x.title[0]}</span><div className="record-copy"><span className="category">RECOMMENDED</span><h3>{x.title}</h3><p>{x.subtitle}</p><div className="skill-row">{String(x.meta.skills||"").split(", ").map(s=><span key={s}>{s}</span>)}</div></div><div className="record-actions"><span className={`state ${x.status}`}>{x.status}</span>{role==="Student"&&<button className="primary" onClick={()=>action(x,"applied")}>{x.status==="applied"?"Application sent":"Apply now"}</button>}</div></article>}/></>}
function CalendarView({records}:{records:RecordItem[]}){const days=Array.from({length:35},(_,i)=>i-2);return <div className="two-column calendar-layout"><section className="panel wide"><PanelTitle title="August 2026" sub="Academic calendar" action="Today" click={()=>{}}/><div className="calendar"><div className="weekdays">{"MON TUE WED THU FRI SAT SUN".split(" ").map(x=><b key={x}>{x}</b>)}</div><div className="days">{days.map((d,i)=><div className={d===10?"today":d<1?"muted-day":""} key={i}><span>{d<1?30+d:d}</span>{d===10&&<i>ML Lab</i>}{d===12&&<i className="event-dot">DevFusion</i>}{d===16&&<i className="event-dot">AI Seminar</i>}</div>)}</div></div></section><section className="panel"><PanelTitle title="Upcoming" sub="Next 7 days" action="" click={()=>{}}/>{records.filter(x=>x.kind==="event"||x.kind==="assignment").slice(0,5).map(x=><div className="agenda" key={x.id}><span className={x.kind}>{x.kind==="event"?"◇":"▤"}</span><div><strong>{x.title}</strong><small>{x.subtitle}</small></div></div>)}</section></div>}
function Messages({items,role,create}:{items:RecordItem[];role:Role;create:(x:string)=>void}){const [text,setText]=useState("");return <div className="messages-layout"><aside className="panel conversations"><div className="conversation-search">⌕ Search conversations</div>{items.map((x,i)=><button key={x.id} className={i===0?"selected":""}><span className="avatar">{x.title.split(" ").map(y=>y[0]).slice(0,2).join("")}</span><span><strong>{x.title}</strong><small>{x.subtitle}</small></span></button>)}</aside><section className="panel chat"><div className="chat-head"><span className="avatar">MK</span><div><strong>Dr. Maya Kapoor</strong><small>● Online · Machine Learning</small></div></div><div className="chat-body"><div className="bubble theirs">Hi {people[role].name.split(" ")[0]}, remember to bring your laptop to today’s lab.<small>9:12 AM</small></div><div className="bubble mine">Sure, thank you for the reminder!<small>9:18 AM</small></div>{items.filter(x=>x.status==="sent").map(x=><div className="bubble mine" key={x.id}>{x.subtitle}<small>Just now</small></div>)}</div><form className="chat-input" onSubmit={e=>{e.preventDefault();if(text.trim()){create(text);setText("")}}}><button type="button">＋</button><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message..."/><button type="submit">Send</button></form></section></div>}
function AdminView({records,activity,setModal}:{records:RecordItem[];activity:Activity[];setModal:(x:string)=>void}){return <><div className="stat-grid"><Stat icon="♙" color="blue" label="Total students" value="1,284" detail="+46 this semester"/><Stat icon="♙" color="purple" label="Faculty members" value="86" detail="8 departments"/><Stat icon="◇" color="orange" label="Active records" value={String(records.length)} detail="Across all modules"/><Stat icon="✓" color="green" label="System health" value="99.9%" detail="All services online"/></div><div className="main-grid"><section className="panel"><PanelTitle title="Quick administration" sub="Manage campus operations" action="" click={()=>{}}/><div className="admin-actions">{[["announcement","Publish announcement","Notify the entire campus"],["event","Create campus event","Schedule and manage seats"],["assignment","Add assignment","Create coursework"],["profile","Manage user roles","Students, faculty and staff"]].map(([type,title,sub])=><button key={type} onClick={()=>setModal(type)}><span>＋</span><div><strong>{title}</strong><small>{sub}</small></div><b>→</b></button>)}</div></section><section className="panel"><PanelTitle title="Audit activity" sub="Latest protected actions" action="" click={()=>{}}/><div className="activity-list">{activity.slice(0,8).map(a=><div key={a.id}><span>●</span><p><strong>{a.message}</strong><small>{a.actor}</small></p></div>)}</div></section></div></>}
function Modal({type,close,person,submit}:{type:string;close:()=>void;person:{name:string;sub:string;initials:string};submit:(e:FormEvent<HTMLFormElement>)=>void}){if(type==="profile")return <div className="modal-backdrop" onMouseDown={close}><div className="modal profile-modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><span className="profile-avatar">{person.initials}</span><h2>{person.name}</h2><p>{person.sub}</p><div className="profile-fields"><label>Email<input value={`${person.name.toLowerCase().replaceAll(" ".charAt(0),".")}@northbridge.edu`} readOnly/></label><label>Department<input value="Computer Science & Engineering" readOnly/></label></div><button className="primary full" onClick={close}>Save profile</button></div></div>;
 return <div className="modal-backdrop" onMouseDown={close}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="modal-close" onClick={close}>×</button><span className="form-icon">＋</span><h2>Create {type}</h2><p>Add a new {type} to the campus workspace.</p><input type="hidden" name="kind" value={type}/><label>Title<input name="title" required placeholder={`Enter ${type} title`}/></label><label>Description / details<textarea name="subtitle" required placeholder="Add date, venue, course or useful details"/></label><label>Category<select name="category"><option>Campus</option><option>Academic</option><option>Technology</option><option>Important</option></select></label><button className="primary full" type="submit">Publish {type}</button></form></div>}
function Stat({icon,color,label,value,detail}:{icon:string;color:string;label:string;value:string;detail:string}){return <article className="stat-card"><div className="stat-head"><span className={`tile-icon ${color}`}>{icon}</span><span className="trend up">↗ live</span></div><p>{label}</p><h2>{value}</h2><small>{detail}</small></article>}
function PanelTitle({title,sub,action,click}:{title:string;sub:string;action:string;click:()=>void}){return <div className="panel-title"><div><h3>{title}</h3><p>{sub}</p></div>{action&&<button onClick={click}>{action}</button>}</div>}
function Empty({text}:{text:string}){return <div className="empty"><span>⌕</span><h3>{text}</h3><p>Try changing your search or create a new record.</p></div>}
function Loading(){return <div className="loading"><span/><span/><span/><span/></div>}
function kindFor(active:string){return ({Assignments:"assignment",Events:"event",Admin:"announcement"} as Record<string,string>)[active]||"announcement"}
function singular(active:string){return ({Assignments:"assignment",Events:"event",Admin:"announcement"} as Record<string,string>)[active]||"record"}
function subtitle(active:string,role:Role){const map:Record<string,string>={Overview:`Welcome back, ${people[role].name.split(" ")[0]}. Here’s your campus at a glance.`,Attendance:"Track presence, subject performance and monthly trends.",Assignments:"Create, submit and review academic coursework.",Events:"Discover and manage everything happening on campus.",Placements:"Explore roles, check eligibility and track applications.",Clubs:"Find your community and grow beyond the classroom.",Calendar:"Classes, deadlines and events in one academic calendar.",Messages:"Secure conversations with faculty and campus teams.",Admin:"Manage people, content, permissions and system activity."};return map[active]}
